---
apiVersion: v1
kind: Service
metadata:
  name: longhorn-frontend
  namespace: longhorn-system
spec:
  ipFamilyPolicy: PreferDualStack
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: longhorn
