---
apiVersion: v1
kind: Service
metadata:
  name: longhorn-ui
spec:
  ipFamilyPolicy: PreferDualStack
  selector:
    app: longhorn-frontend
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
