apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openfaas-ingress
spec:
  ingressClassName: nginx # use only with k8s version >= 1.18.0
  tls:
  rules:
  - host: openfaas.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: openfaas-service
            port:
              number: 8080
