apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openfaas-ingress
  namespace: openfaas
spec:
  rules:
  - http:
      paths:
        - path: /open-faas/
          pathType: Prefix
          backend:
            service:
              name: openfaas-service
              port:
                number: 8080
