ingress:
  enabled: true
  annotations:
     cert-manager.io/issuer: letsencrypt-prod

     kubernetes.io/ingress.class: traefik
     kubernetes.io/tls-acme: "true"
  hosts:
    - host: gitea.cube.local
      paths:
        - path: /
          pathType: Prefix
  tls:
  - secretName: gitea-tls
    hosts:
        - gitea.cube.local
service:
  http:
    type: ClusterIP
    port: 3000
    clusterIP: None
  ssh:
    type: LoadBalancer
    port: 2222
    clusterIP: None

gitea:
  admin:
    existingSecret: gitea-admin-secret
    email: davidwazny19@gmail.com
  config:
    server:
      SSH_DOMAIN: gitea-ssh.cube.local
    service:
      DISABLE_REGISTRATION: true
      SHOW_REGISTRATION_BUTTON: false
