apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard-service

spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: dashboard
  selector:
    app: traefik
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-web-service

spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.91
  ports:
    - protocol: TCP
      targetPort: web
      port: 80
  selector:
    app: traefik
