apiVersion: v1
kind: Secret
metadata:
  name: ddclient-secret
  labels:
    app: ddclient
stringData:
  ddclient.conf: |
    daemon=300
    syslog=yes
    protocol=freedns
    use=web
    web=https://domains.google.com/checkip
    ssl=yes
    ttl=1
    login=dwazny25
    password='Paper0s!horse2'
    waznyvpn.crabdance.com
