---
- name: Configure systemd-resolved
  hosts: localhost
  become: yes

  tasks:
    - name: Set DNS and DOMAINS in resolved.conf
      lineinfile:
        path: /etc/systemd/resolved.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        insertafter: "{{ item.insertafter | default('EOF') }}"
      with_items:
        - { regexp: '^#?DNS=', line: 'DNS=192.168.1.1', insertafter: '^#?DNS=' }
        - { regexp: '^#?Domains=', line: 'Domains=cube.local', insertafter: '^#?Domains=' }
        - { regexp: '^#?FallbackDNS=', line: 'FallbackDNS=8.8.8.8', insertafter: '^#?FallbackDNS=' }

    - name: Restart systemd-resolved
      systemd:
        name: systemd-resolved
        state: restarted
